[package]
name = "kry"
version = "0.1.0"
authors = ["honza"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.2"
pest-ast = "0.3.3"
pest_derive = "2.1.0"
colored = "1.8"
